name: Deploy to GAE


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Build and Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
            actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '18.x'

    - name: Build
      run: |
        npm install n -g
        npm install
        npm install -g @angular/cli
        ng build --prod

    - name: Upload Folder
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist'
        destination: 'vtai-todo'

    - name: Upload File
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'app.yaml'
        destination: 'vtai-todo/app.yaml'

    - name: Load Config Files
      run: |
          echo "${{secrets.VTAI_CONFIG}}" | base64 --decode > .env 

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
