name: Deploy to GAE


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Build and Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '18.x'
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    

    - name: Build
      run: |
        npm install --save --legacy-peer-deps
        npm install -g @angular/cli
        ng build
        
    - name: Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Upload Folder
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist'
        destination: 'vtai-todo'
        
    - name: Upload File
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'app.yaml'
        destination: 'vtai-todo'

    - name: Load Config Files
      run: |
          echo "${{secrets.VTAI_CONFIG}}" | base64 --decode > .env 
    
    - name: Create Directory
      run : | 
          mkdir vtai-todo-app
          cd vtai-todo-app
          
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
          
    - name: Use gcloud CLI
      run : gsutil rsync -r gs://vtai-todo ./vtai-todo-app

    - name: Move to Directory
      run : | 
          cd vtai-todo-app
          
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
